### ISSUE TITLE
Rendering Todo component as simple component

### ISSUE THREAD

**Issue by msteele96** [learn-co-curriculum/redux-index-codealong#38]
In the code along we are instructed to render the Todo component like this: 
`renderTodos = () => this.props.todos.map((todo, id) => <Todo key={id} text={todo} />)`

I've tried rendering a simple component this way a few times and it has been unsuccessful for me. The way that I've gotten it to render is by actually invoking Todo(props). 
`renderTodos = () => this.props.todos.map((todo) => Todo(todo))`

My repo is at: https://github.com/msteele96/redux-index-codealong-online-web-sp-000

I'd love to hear if this is a legitimate problem with rendering or if there is some other error in my code that forced me to find this workaround.

**Comment by ihollander** [comment]
Hi @msteele96 , thanks for your question! After review, it doesn't appear they are any issues with the code in the readme. In your code it appears the issue is in your Todo component:

```js
const Todo = props => {
  return (
    <li>{props}</li>
  );
};
```

Try and make sure your code matches the code from the codealong exactly.
